### ISSUE TITLE
Make sure ps_themecusto is compatible with 1.7.6 + new categories page

### ISSUE THREAD

**Issue by matks** [PrestaShop/ps_themecusto#10]
Categories page has been migrated (Symfony) - we need to be sure the link to this page is correct.

See https://github.com/PrestaShop/PrestaShop/issues/10193#issuecomment-418310586

**Comment by marionf** [comment]
It's ok for categories, we are well redireted to symfony page

![capture d'écran_1356](https://user-images.githubusercontent.com/13449658/55894857-479d1680-5bbb-11e9-9524-72a8803c03a5.png)

**Comment by marionf** [comment]
We can close it, but I can't do it @matks

**Comment by matks** [comment]
> We can close it, but I can't do it @matks

You need to ask for the right to el jefe !
