### ISSUE TITLE
Make sure ps_themecusto is compatible with 1.7.6 + new brand page 

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/ps_themecusto#9]
Brand & Suppliers page has been migrated (Symfony) - we need to be sure the link to this page is correct.

**Comment by marionf** [comment]
It's ok for Brands & supplier, we are well redirected to symfony page

![capture d'écran_1355](https://user-images.githubusercontent.com/13449658/55894762-0dcc1000-5bbb-11e9-8a6b-149530da9ec2.png)

**Comment by jolelievre** [comment]
I also check it it's ok Should we close this issue?

**Comment by marionf** [comment]
Yes, but I can't do it :)
